name: test

on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
      - release/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Aikido Safe Chain
      run: |
          npm i -g @aikidosec/safe-chain
          safe-chain setup-ci

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm run test
